### ISSUE TITLE
user: 닉네임 추가해주세요

### ISSUE THREAD

**Issue by KimSoapSoap** [KimSoapSoap/bookbox-api#6]
리뷰 쓸 때 닉네임 노출하게 할 거에용

**Comment by KimSoapSoap** [comment]
회원가입시 아이디 중복검사 확인해주는 주소랑
닉네임 중복검사 확인해주는 주소
만들어 주세요

중복검사 버튼 누르면 서버에 요청해서 중복인지 확인하려고 합니다

**Comment by HJK0000** [comment]
넹 API 문서에 추가했습니다~~
